In [2]:
#Insert 1 to 100 numbers in a numpy array and reshape it to 10*10 matrix.

import numpy as np
from numpy import random
x = random.randint(100, size=(10,10))
print("Insert 1 to 100 numbers in a numpy array and reshape it to 10*10 matrix: ",x)

Insert 1 to 100 numbers in a numpy array and reshape it to 10*10 matrix:  [[61 97 81 16  6 88  6 72 98 72]
 [ 8 88 45 42 67 36 86 89 63 15]
 [19 94 98 52 63 56 38 61 67 34]
 [38 91 89 89 87 53 93 20 51 47]
 [12 58 72 64 43 46 58 40 59 31]
 [15 24 45 70 72 25 26 93  6 44]
 [54 59 79 36 73 11 10 16 48 55]
 [69 88 54 39 28 84  4 49  1 16]
 [ 4 93 87 13 43 53 62 90 20 48]
 [74  7 50  9 29 14 43 94 91 40]]
