In [3]:
# Create a 10x10 array with random values and find the minimum and maximum values.

import numpy as np
from numpy import random
a = random.randint(1000,size=(10,10))
print("The orignal array: ")
print(a)
amin,amax=a.min(),a.max()
print("Minimum Value :",amin)
print("Maximum Value: ",amax)

The orignal array: 
[[862 632 578 628 135 422 707 877 910 512]
 [813 446 727 727 294   2 657 722 107  90]
 [144 469 686 123 767  75  89 294 559 312]
 [807  76 249 802 534 199 218 319 344 863]
 [261  65 923 522 805 304 743 391 555 429]
 [877 444 481 145 668  84 757 992 887 621]
 [465 903 690 168 735 653 531 511 598 315]
 [415 972 728 812 771 374 629 640 481 784]
 [219 180 435  38 222 906 361 571 509 859]
 [749 479 248 616 774 322 753 294 282  50]]
Minimum Value : 2
Maximum Value:  992
